name: Apache Benchmark

# Controls when the action will run.
# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: ./bench-ab.sh

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: bench-${{ matrix.os }}
          path: ./ab.log