name: Spring WebFlux and JMH benchmarking

# Controls when the action will run. 
# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    runs-on:
      labels: ubuntu-20.04-64core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark
        run: java -jar target/template-engines.jar -i 4 -wi 4 -f 1 -r 2 -w 2 -t 64 -rff results.csv -rf csv

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: bench-results-${{ matrix.os }}-${{ matrix.workload }}
          path: ./results.csv
